function [stress_enz,...      
          sigma_vector,...     
          sigma,...
          tau,...
          mean_stress,...
          coulomb_stress,...
          coulomb_stress_pore] = ...
  read_cal_stress_qssp( path_green,...
                    sub_fm,...
                    source_point,...
                    field_point,...
                    n_obs,...
                    d_obs,...
                    points_green_geo,...
                    event_dep_list,...
                    receiver_dep_list,...
                    srate_cfs,...
                    time_reduction,...
                    N_T)
% READ_STRESS_QSSP read the stress results calculated by pygrnwang, using
%                  python codes (Zhou Jiangcheng, 2024.11.29)
% path_green: Path of the Green's Func Libarary (Lib)
% sub_fm: Focal mechanism of the source point
% source_point: [Lat(deg), Lon(deg), Dep(km)] of the source point
% field_point: [Lat(deg), Lon(deg), Dep(km)] of the field point
% n_obs: Normal vector of the plane at the field point, in NED axis
% d_obs: Slip direction at the field point, in NED axis
% points_green_geo: Points location the Green's Function Lib contains,
%                   [[x1,y1];...;[xn,yn]] be reshaped to 
%                   [x1,x2,...,xn,y1,y2,...,yn] to conveniently transfer to
%                   python function
% event_dep_list: Depth(km) list of sources
% receiver_dep_list: Depth(km) list of receivers
% srate_cfs: Sampling rate of dynamic stress in the Lib
% time_reduction: Time before the origin time in the Lib
% N_T: Time points num in the Lib

np = py.importlib.import_module('numpy');
cfs_lib = py.importlib.import_module('coulomb_failure_stress_change');

py_tuple=cfs_lib.coulomb_stress_dynamic.cal_coulomb_stress_grn_point2point( ...
    path_green,...
    np.array(sub_fm),...
    np.array(source_point),...
    np.array(field_point),...
    np.array(points_green_geo),...
    np.array(event_dep_list),...
    np.array(receiver_dep_list),...
    srate_cfs,...
    time_reduction,...
    N_T,...
    np.array(n_obs),...
    np.array(d_obs));

stress_enz=double(np.array(py_tuple(1)));
sigma_vector=double(np.array(py_tuple(2)));
sigma=double(np.array(py_tuple(3)));
tau=double(np.array(py_tuple(4)));
mean_stress=double(np.array(py_tuple(5)));
coulomb_stress=double(np.array(py_tuple(6)));
coulomb_stress_pore=double(np.array(py_tuple(7)));
end